# Setup
title: kbdnr
url: https://kbdnr.github.io
paginate: 1
paginate_path: "/page:num/"
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Kevin Bednar
  url: https://twitter.com/spednar
  email: info@spednar.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Calendar
    url: /calendar

  - title: About
    url: /about

  - title: Archive
    url: /archive
